export const actions = {
    GET_ALL_POKEMONS: "GET_ALL_POKEMONS",
    GET_POKEMON_BY_NAME: "GET_POKEMON_BY_NAME",
    GET_POKEMON_BY_ID: "GET_POKEMON_BY_ID",
    GET_ALL_TYPES: "GET_ALL_TYPES",
    POST_A_NEW_POKEMON: "POST_A_NEW_POKEMON",
    DELETE_POKEMON: "DELETE_POKEMON", //////////////////////////////////
    FILTER_BY_TYPES: "FILTER_BY_TYPES",
    FILTER_POKEMON_CREATED: "FILTER_POKEMON_CREATED",
    ORDER_A_TO_Z: "ORDER_A_TO_Z",
    ORDER_Z_TO_A: "ORDER_Z_TO_A",
    ORDER_BY_ATTACK: "ORDER_BY_ATTACK",
    RESET_FILTERS: "RESET_FILTERS"
}